#服务器端口
server:
  port: 8080
  
spring: 
  application: 
    name: client

 #----------------------------消息队列RabbitMQ配置-----------------------------------------
  rabbitmq: 
    host: 192.168.137.24
    port: 5672
    username: admin
    password: admin
    listener: 
      #设置rabbitmq重试（ACK确认机制，如果无线重发，会导致rabbitmq内存泄露）
      simple:
        retry: 
          enabled: true           #开启失败重试  
          max-attempts: 5         #最大重试次数  
          initial-interval: 1000  #重试间隔时间 毫秒
    
